### ISSUE TITLE
Can't build .deb : dpkg-source: error: can't build with source format '3.0 (native)'

### ISSUE THREAD

**Issue by Lyro1** [log2timeline/l2tdevtools#468] opened 2018-10-02 15:32 UTC
My context
-
I am trying to install Plaso on a Debian 9 distribution by creating a little script that could deploy easily the software and its dependencies on any Debian 9 plateform.

My issue
-
I am trying to build plaso with the build script provided in the l2tdevtools repository, and I am facing this issue: when I run the following command
`PYTHONPATH=. python tools/build.py --preset plaso dpkg`.
all the build fail with an error message saying that *flex, byacc, python3-all, python3-setuptools* and *python3-all-dev* are missing dependencies.

So I added those packages to the list of dependencies, which then looked like so:
```
sudo apt-get install build-essential autoconf automake autopoint libtool gettext pkg-config debhelper devscripts fakeroot quilt autotools-dev zlib1g-dev libbz2-dev libssl-dev libfuse-dev libfuse-dev python-dev python-setuptools flex byacc python3-all python3-setuptools python3-all-dev -y
```
Then, when I ran the previous command, some packages were successfully created, but some failed. 

For example, the first one that fails is **backport.lzma**, with the following message:
```[ERROR] Failed to run: "(cd backports.lzma-0.0.13 && dpkg-buildpackage -uc -us -rfakeroot > ../build.log 2>&1" with exit code 3.```
When I opened the log file, I got this:
```$ cat backports.lzma_build.log 
dpkg-buildpackage: info: paquet source backports.lzma
dpkg-buildpackage: info: version source 0.0.13-1
dpkg-buildpackage: info: distribution source unstable
dpkg-buildpackage: info: source changé par log2timeline development team <log2timeline-dev@googlegroups.com>
 dpkg-source --before-build backports.lzma-0.0.13
dpkg-buildpackage: info: architecture hôte amd64
dpkg-checkbuilddeps: erreur: Unmet build dependencies: liblzma-dev
dpkg-buildpackage: avertissement: dépendances de construction et conflits non satisfaits ; échec.
dpkg-buildpackage: avertissement: (Utilisez l'option -d pour forcer.)
```
I am sorry but the laptop I am working on is in french, so some lines are in french. However, the main problem was clear: the *liblzma-dev* was missing. I added it to the command line you provided in the documentation, which was then:
```
sudo apt-get install build-essential autoconf automake autopoint libtool gettext pkg-config debhelper devscripts fakeroot quilt autotools-dev zlib1g-dev libbz2-dev libssl-dev libfuse-dev libfuse-dev python-dev python-setuptools flex byacc python3-all python3-setuptools python3-all-dev liblzma-dev -y
```
I ran the script again, and got another error message on the same package:
```
[ERROR] Failed to run: "(cd backports.lzma-0.0.13 && dpkg-buildpackage -uc -us -rfakeroot > ../build.log 2>&1" with exit code 255.
```
So I looked again in the .log file, and got the following output:
```
$ cat backports.lzma_build.log 
dpkg-buildpackage: info: paquet source backports.lzma
dpkg-buildpackage: info: version source 0.0.13-1
dpkg-buildpackage: info: distribution source unstable
dpkg-buildpackage: info: source changé par log2timeline development team <log2timeline-dev@googlegroups.com>
 dpkg-source --before-build backports.lzma-0.0.13
dpkg-buildpackage: info: architecture hôte amd64
 fakeroot debian/rules clean
dh clean --buildsystem=pybuild --with=python2
dh: Compatibility levels before 9 are deprecated (level 7 in use)
   dh_testdir -O--buildsystem=pybuild
   dh_auto_clean -O--buildsystem=pybuild
dh_auto_clean: Compatibility levels before 9 are deprecated (level 7 in use)
I: pybuild base:184: python2.7 setup.py clean 
This is backports.lzma version 0.0.13
running clean
removing '/home/d594416/Documents/git/image_analysis/l2tdevtools/build/backports.lzma-0.0.13/.pybuild/pythonX.Y_2.7/build' (and everything under it)
'build/bdist.linux-amd64' does not exist -- can't clean it
'build/scripts-2.7' does not exist -- can't clean it
   dh_clean -O--buildsystem=pybuild
dh_clean: Compatibility levels before 9 are deprecated (level 7 in use)
 dpkg-source -b backports.lzma-0.0.13
dpkg-source: erreur: impossible de construire avec le format source « 3.0 (native) » : la version du paquet natif ne peut avoir de numéro de révision
dpkg-buildpackage: erreur: dpkg-source -b backports.lzma-0.0.13 a produit une erreur de sortie de type 255
```
I googled a little about this dpkg-source error, it seems like this is a problem with the dpkg-source call, but I want to be sure that all those previous dependencies issues that I was facing are not the reason why this error is rising.

**Comment by joachimmetz** [comment] 2018-10-02 17:41
Google translate

```
dpkg-source: error: impossible to build with source format "3.0 (native)": native package version can not have revision number
dpkg-buildpackage: error: dpkg-source -b backports.lzma-0.0.13 produced an output error of type 255
```

So this is a difference between Debian and Ubuntu where Debian is more strict what the version of package in source format "3.0 (native)" should be. Could you check if you need to build this, or that Debian already provides a backports.lzma package

**Comment by joachimmetz** [comment] 2018-10-02 17:50
Related: https://github.com/log2timeline/l2tdevtools/issues/268

**Comment by Lyro1** [comment] 2018-10-03 07:41
I searched for a potential *backport.lzma* that could be provided by default, but found none
```
$ dpkg-query -l '*lzma*'
Souhait=inconnU/Installé/suppRimé/Purgé/H=à garder
| État=Non/Installé/fichier-Config/dépaqUeté/échec-conFig/H=semi-installé/W=attend-traitement-déclenchements
|/ Err?=(aucune)/besoin Réinstallation (État,Err: majuscule=mauvais)
||/ Name           Version      Architecture Description
+++-==============-============-============-=================================
ii  liblzma-dev:am 5.2.2-1.2+b1 amd64        XZ-format compression library - d
un  liblzma-doc    <none>       <none>       (no description available)
ii  liblzma5:amd64 5.2.2-1.2+b1 amd64        XZ-format compression library
un  lzma           <none>       <none>       (no description available)
ii  python-lzma    0.5.3-3      amd64        Python bindings for liblzma
un  python2.7-lzma <none>       <none>       (no description available)
un  xz-lzma        <none>       <none>       (no description available)

```
I searched a little bit and found that it was a Python library that could be installed either by using pip or by compiling it in the old fashioned way.
Are you using pip to manage your Python packages, or should I compile it manually like indicated [here](https://github.com/peterjc/backports.lzma#installation) ?
Also, to remove this package from the build list, should I remove it from the projects.ini file ?

**Comment by Lyro1** [comment] 2018-10-03 08:30
Note that the following packages have the same error : 
- **backport.lzma**
- **elasticsearch5-py**
- **guppy**
- **hachoir-core**
- **hachoir-metadata**
- **hachoir-parser**

**Comment by joachimmetz** [comment] 2018-10-03 09:14
> I searched for a potential backport.lzma that could be provided by default, but found none

Could be that this is not available on Debian, unfortunately.

So installing Python modules with pip is not recommended since it will (very likely at some point) conflict with your system installed packages. If you use virtualenv with pip you should be fine.

So backport.lzma, hachoir-core, hachoir-metadata and hachoir-parser are optional plaso dependencies.

guppy is for development purposes. 

elasticsearch5-py is needed if you want to run with Timesketch.

I'll try to have a look at the Debian package process as soon as time permits.

**Comment by joachimmetz** [comment] 2018-12-26 21:58
Duplicate of https://github.com/log2timeline/l2tdevtools/issues/268. Closing this issue

**Closed by joachimmetz** 2018-12-26 21:58 UTC
Labels: question
