### ISSUE TITLE
yara-python build error for msi target

### ISSUE THREAD

**Issue by Onager** [log2timeline/l2tdevtools#646] opened 2019-03-30 17:03 UTC
```
[INFO] Building: yara-python
[WARNING] Missing build helper.
Detected error in configuration of: yara-python
Failed building: yara-python

Projects with configuration errors:
	yara-python

Failed building:
	yara-python
Error building dependencies
At C:\Users\plaso_test\AppData\Local\Temp\jenkins1095986082593405263.ps1:6 char:3
+   throw "Error building dependencies"
+   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Error building dependencies:String) [], RuntimeException
    + FullyQualifiedErrorId : Error building dependencies
```

**Comment by joachimmetz** [comment] 2019-03-30 17:50
Duplicate of https://github.com/log2timeline/l2tdevtools/issues/605

**Closed by joachimmetz** 2019-03-30 17:50 UTC
